require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LineupsController do

  # This should return the minimal set of attributes required to create a valid
  # Lineup. As you add validations to Lineup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LineupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all lineups as @lineups" do
      lineup = Lineup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lineups).should eq([lineup])
    end
  end

  describe "GET show" do
    it "assigns the requested lineup as @lineup" do
      lineup = Lineup.create! valid_attributes
      get :show, {:id => lineup.to_param}, valid_session
      assigns(:lineup).should eq(lineup)
    end
  end

  describe "GET new" do
    it "assigns a new lineup as @lineup" do
      get :new, {}, valid_session
      assigns(:lineup).should be_a_new(Lineup)
    end
  end

  describe "GET edit" do
    it "assigns the requested lineup as @lineup" do
      lineup = Lineup.create! valid_attributes
      get :edit, {:id => lineup.to_param}, valid_session
      assigns(:lineup).should eq(lineup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lineup" do
        expect {
          post :create, {:lineup => valid_attributes}, valid_session
        }.to change(Lineup, :count).by(1)
      end

      it "assigns a newly created lineup as @lineup" do
        post :create, {:lineup => valid_attributes}, valid_session
        assigns(:lineup).should be_a(Lineup)
        assigns(:lineup).should be_persisted
      end

      it "redirects to the created lineup" do
        post :create, {:lineup => valid_attributes}, valid_session
        response.should redirect_to(Lineup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lineup as @lineup" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lineup.any_instance.stub(:save).and_return(false)
        post :create, {:lineup => {}}, valid_session
        assigns(:lineup).should be_a_new(Lineup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lineup.any_instance.stub(:save).and_return(false)
        post :create, {:lineup => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lineup" do
        lineup = Lineup.create! valid_attributes
        # Assuming there are no other lineups in the database, this
        # specifies that the Lineup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lineup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => lineup.to_param, :lineup => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested lineup as @lineup" do
        lineup = Lineup.create! valid_attributes
        put :update, {:id => lineup.to_param, :lineup => valid_attributes}, valid_session
        assigns(:lineup).should eq(lineup)
      end

      it "redirects to the lineup" do
        lineup = Lineup.create! valid_attributes
        put :update, {:id => lineup.to_param, :lineup => valid_attributes}, valid_session
        response.should redirect_to(lineup)
      end
    end

    describe "with invalid params" do
      it "assigns the lineup as @lineup" do
        lineup = Lineup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lineup.any_instance.stub(:save).and_return(false)
        put :update, {:id => lineup.to_param, :lineup => {}}, valid_session
        assigns(:lineup).should eq(lineup)
      end

      it "re-renders the 'edit' template" do
        lineup = Lineup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lineup.any_instance.stub(:save).and_return(false)
        put :update, {:id => lineup.to_param, :lineup => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lineup" do
      lineup = Lineup.create! valid_attributes
      expect {
        delete :destroy, {:id => lineup.to_param}, valid_session
      }.to change(Lineup, :count).by(-1)
    end

    it "redirects to the lineups list" do
      lineup = Lineup.create! valid_attributes
      delete :destroy, {:id => lineup.to_param}, valid_session
      response.should redirect_to(lineups_url)
    end
  end

end
