require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PracticesController do

  # This should return the minimal set of attributes required to create a valid
  # Practice. As you add validations to Practice, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PracticesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all practices as @practices" do
      practice = Practice.create! valid_attributes
      get :index, {}, valid_session
      assigns(:practices).should eq([practice])
    end
  end

  describe "GET show" do
    it "assigns the requested practice as @practice" do
      practice = Practice.create! valid_attributes
      get :show, {:id => practice.to_param}, valid_session
      assigns(:practice).should eq(practice)
    end
  end

  describe "GET new" do
    it "assigns a new practice as @practice" do
      get :new, {}, valid_session
      assigns(:practice).should be_a_new(Practice)
    end
  end

  describe "GET edit" do
    it "assigns the requested practice as @practice" do
      practice = Practice.create! valid_attributes
      get :edit, {:id => practice.to_param}, valid_session
      assigns(:practice).should eq(practice)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Practice" do
        expect {
          post :create, {:practice => valid_attributes}, valid_session
        }.to change(Practice, :count).by(1)
      end

      it "assigns a newly created practice as @practice" do
        post :create, {:practice => valid_attributes}, valid_session
        assigns(:practice).should be_a(Practice)
        assigns(:practice).should be_persisted
      end

      it "redirects to the created practice" do
        post :create, {:practice => valid_attributes}, valid_session
        response.should redirect_to(Practice.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved practice as @practice" do
        # Trigger the behavior that occurs when invalid params are submitted
        Practice.any_instance.stub(:save).and_return(false)
        post :create, {:practice => {}}, valid_session
        assigns(:practice).should be_a_new(Practice)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Practice.any_instance.stub(:save).and_return(false)
        post :create, {:practice => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested practice" do
        practice = Practice.create! valid_attributes
        # Assuming there are no other practices in the database, this
        # specifies that the Practice created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Practice.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => practice.to_param, :practice => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested practice as @practice" do
        practice = Practice.create! valid_attributes
        put :update, {:id => practice.to_param, :practice => valid_attributes}, valid_session
        assigns(:practice).should eq(practice)
      end

      it "redirects to the practice" do
        practice = Practice.create! valid_attributes
        put :update, {:id => practice.to_param, :practice => valid_attributes}, valid_session
        response.should redirect_to(practice)
      end
    end

    describe "with invalid params" do
      it "assigns the practice as @practice" do
        practice = Practice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Practice.any_instance.stub(:save).and_return(false)
        put :update, {:id => practice.to_param, :practice => {}}, valid_session
        assigns(:practice).should eq(practice)
      end

      it "re-renders the 'edit' template" do
        practice = Practice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Practice.any_instance.stub(:save).and_return(false)
        put :update, {:id => practice.to_param, :practice => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested practice" do
      practice = Practice.create! valid_attributes
      expect {
        delete :destroy, {:id => practice.to_param}, valid_session
      }.to change(Practice, :count).by(-1)
    end

    it "redirects to the practices list" do
      practice = Practice.create! valid_attributes
      delete :destroy, {:id => practice.to_param}, valid_session
      response.should redirect_to(practices_url)
    end
  end

end
