require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RaceLineupsController do

  # This should return the minimal set of attributes required to create a valid
  # RaceLineup. As you add validations to RaceLineup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RaceLineupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all race_lineups as @race_lineups" do
      race_lineup = RaceLineup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:race_lineups).should eq([race_lineup])
    end
  end

  describe "GET show" do
    it "assigns the requested race_lineup as @race_lineup" do
      race_lineup = RaceLineup.create! valid_attributes
      get :show, {:id => race_lineup.to_param}, valid_session
      assigns(:race_lineup).should eq(race_lineup)
    end
  end

  describe "GET new" do
    it "assigns a new race_lineup as @race_lineup" do
      get :new, {}, valid_session
      assigns(:race_lineup).should be_a_new(RaceLineup)
    end
  end

  describe "GET edit" do
    it "assigns the requested race_lineup as @race_lineup" do
      race_lineup = RaceLineup.create! valid_attributes
      get :edit, {:id => race_lineup.to_param}, valid_session
      assigns(:race_lineup).should eq(race_lineup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RaceLineup" do
        expect {
          post :create, {:race_lineup => valid_attributes}, valid_session
        }.to change(RaceLineup, :count).by(1)
      end

      it "assigns a newly created race_lineup as @race_lineup" do
        post :create, {:race_lineup => valid_attributes}, valid_session
        assigns(:race_lineup).should be_a(RaceLineup)
        assigns(:race_lineup).should be_persisted
      end

      it "redirects to the created race_lineup" do
        post :create, {:race_lineup => valid_attributes}, valid_session
        response.should redirect_to(RaceLineup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved race_lineup as @race_lineup" do
        # Trigger the behavior that occurs when invalid params are submitted
        RaceLineup.any_instance.stub(:save).and_return(false)
        post :create, {:race_lineup => {}}, valid_session
        assigns(:race_lineup).should be_a_new(RaceLineup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RaceLineup.any_instance.stub(:save).and_return(false)
        post :create, {:race_lineup => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested race_lineup" do
        race_lineup = RaceLineup.create! valid_attributes
        # Assuming there are no other race_lineups in the database, this
        # specifies that the RaceLineup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RaceLineup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => race_lineup.to_param, :race_lineup => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested race_lineup as @race_lineup" do
        race_lineup = RaceLineup.create! valid_attributes
        put :update, {:id => race_lineup.to_param, :race_lineup => valid_attributes}, valid_session
        assigns(:race_lineup).should eq(race_lineup)
      end

      it "redirects to the race_lineup" do
        race_lineup = RaceLineup.create! valid_attributes
        put :update, {:id => race_lineup.to_param, :race_lineup => valid_attributes}, valid_session
        response.should redirect_to(race_lineup)
      end
    end

    describe "with invalid params" do
      it "assigns the race_lineup as @race_lineup" do
        race_lineup = RaceLineup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RaceLineup.any_instance.stub(:save).and_return(false)
        put :update, {:id => race_lineup.to_param, :race_lineup => {}}, valid_session
        assigns(:race_lineup).should eq(race_lineup)
      end

      it "re-renders the 'edit' template" do
        race_lineup = RaceLineup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RaceLineup.any_instance.stub(:save).and_return(false)
        put :update, {:id => race_lineup.to_param, :race_lineup => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested race_lineup" do
      race_lineup = RaceLineup.create! valid_attributes
      expect {
        delete :destroy, {:id => race_lineup.to_param}, valid_session
      }.to change(RaceLineup, :count).by(-1)
    end

    it "redirects to the race_lineups list" do
      race_lineup = RaceLineup.create! valid_attributes
      delete :destroy, {:id => race_lineup.to_param}, valid_session
      response.should redirect_to(race_lineups_url)
    end
  end

end
