require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RowersController do

  # This should return the minimal set of attributes required to create a valid
  # Rower. As you add validations to Rower, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RowersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all rowers as @rowers" do
      rower = Rower.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rowers).should eq([rower])
    end
  end

  describe "GET show" do
    it "assigns the requested rower as @rower" do
      rower = Rower.create! valid_attributes
      get :show, {:id => rower.to_param}, valid_session
      assigns(:rower).should eq(rower)
    end
  end

  describe "GET new" do
    it "assigns a new rower as @rower" do
      get :new, {}, valid_session
      assigns(:rower).should be_a_new(Rower)
    end
  end

  describe "GET edit" do
    it "assigns the requested rower as @rower" do
      rower = Rower.create! valid_attributes
      get :edit, {:id => rower.to_param}, valid_session
      assigns(:rower).should eq(rower)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Rower" do
        expect {
          post :create, {:rower => valid_attributes}, valid_session
        }.to change(Rower, :count).by(1)
      end

      it "assigns a newly created rower as @rower" do
        post :create, {:rower => valid_attributes}, valid_session
        assigns(:rower).should be_a(Rower)
        assigns(:rower).should be_persisted
      end

      it "redirects to the created rower" do
        post :create, {:rower => valid_attributes}, valid_session
        response.should redirect_to(Rower.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rower as @rower" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rower.any_instance.stub(:save).and_return(false)
        post :create, {:rower => {}}, valid_session
        assigns(:rower).should be_a_new(Rower)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rower.any_instance.stub(:save).and_return(false)
        post :create, {:rower => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rower" do
        rower = Rower.create! valid_attributes
        # Assuming there are no other rowers in the database, this
        # specifies that the Rower created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Rower.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => rower.to_param, :rower => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested rower as @rower" do
        rower = Rower.create! valid_attributes
        put :update, {:id => rower.to_param, :rower => valid_attributes}, valid_session
        assigns(:rower).should eq(rower)
      end

      it "redirects to the rower" do
        rower = Rower.create! valid_attributes
        put :update, {:id => rower.to_param, :rower => valid_attributes}, valid_session
        response.should redirect_to(rower)
      end
    end

    describe "with invalid params" do
      it "assigns the rower as @rower" do
        rower = Rower.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rower.any_instance.stub(:save).and_return(false)
        put :update, {:id => rower.to_param, :rower => {}}, valid_session
        assigns(:rower).should eq(rower)
      end

      it "re-renders the 'edit' template" do
        rower = Rower.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rower.any_instance.stub(:save).and_return(false)
        put :update, {:id => rower.to_param, :rower => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rower" do
      rower = Rower.create! valid_attributes
      expect {
        delete :destroy, {:id => rower.to_param}, valid_session
      }.to change(Rower, :count).by(-1)
    end

    it "redirects to the rowers list" do
      rower = Rower.create! valid_attributes
      delete :destroy, {:id => rower.to_param}, valid_session
      response.should redirect_to(rowers_url)
    end
  end

end
